/**
 * @file settings-tab.ts
 * @description
 * The main configuration UI for the plugin.
 * * AI CONTEXT & ARCHITECTURE NOTE:
 * This UI manages the 1-hour Custom Token exchange. The user pastes the code generated by
 * the React app, clicks "Connect", and the SDK trades it for a permanent Refresh Token via
 * Google Identity Toolkit. The 1-hour code is immediately discarded.
 */

import { App, PluginSettingTab, Setting, Notice } from 'obsidian';
import SelfStatsPlugin from '../main';

export class SelfStatsSettingTab extends PluginSettingTab {
    plugin: SelfStatsPlugin;

    constructor(app: App, plugin: SelfStatsPlugin) {
        super(app, plugin);
        this.plugin = plugin;
    }

    display(): void {
        const {containerEl} = this;
        containerEl.empty();

        new Setting(containerEl).setName('Connection configuration').setHeading();

        new Setting(containerEl)
            .setName('Firebase project ID')
            .setDesc('Your firebase project identifier.')
            .addText(text => text
                // eslint-disable-next-line obsidianmd/ui/sentence-case
                .setPlaceholder('self-statistics-system-v2')
                .setValue(this.plugin.settings.projectId)
                .onChange(async (value) => {
                    this.plugin.settings.projectId = value;
                    await this.plugin.saveSettings();
                    this.plugin.initializeSdk(); 
                }));

        new Setting(containerEl)
            .setName('Firebase API key')
            .setDesc('Your public web API key from firebase.')
            .addText(text => text
                // eslint-disable-next-line obsidianmd/ui/sentence-case
                .setPlaceholder('AIzaSy...')
                .setValue(this.plugin.settings.apiKey)
                .onChange(async (value) => {
                    this.plugin.settings.apiKey = value;
                    await this.plugin.saveSettings();
                    this.plugin.initializeSdk(); 
                }));

        new Setting(containerEl)
            .setName('Backend endpoint')
            .setDesc('Local emulator or live cloud function endpoint.')
            .addText(text => text
                // // eslint-disable-next-line obsidianmd/ui/sentence-case
                .setPlaceholder('http://127.0.0.1:5001/...')
                .setValue(this.plugin.settings.backendUrl)
                .onChange(async (value) => {
                    this.plugin.settings.backendUrl = value;
                    await this.plugin.saveSettings();
                    this.plugin.initializeSdk();
                }));

        new Setting(containerEl).setName('Authentication').setHeading();
        
        let setupCodeInput = "";

        new Setting(containerEl)
            .setName('Connect integration')
            .setDesc(this.plugin.settings.authData 
                ? 'System is authenticated. Generate a new setup code to overwrite.' 
                : 'Paste your 1-hour setup code from the react dashboard.')
            .addText(text => text
                .setPlaceholder('Setup code')
                .onChange(value => {
                    setupCodeInput = value;
                }))
            .addButton(button => button
                .setButtonText('Connect')
                .setCta()
                .onClick(async () => {
                    if (!setupCodeInput) {
                        new Notice("Please enter a setup code first.");
                        return;
                    }

                    // Fix: Prevent connecting if the SDK hasn't booted yet
                    if (!this.plugin.client) {
                        new Notice("Please fill out the connection configuration first.");
                        return;
                    }
                    
                    button.setButtonText("Connecting...");
                    button.setDisabled(true);

                    try {
                        await this.plugin.client.exchangeCustomToken(setupCodeInput);
                        new Notice("Authentication successful.");
                        this.display(); 
                    } catch (error) {
                        console.error(error);
                        new Notice("Failed to connect. Check the console for details.");
                        button.setButtonText("Connect");
                        button.setDisabled(false);
                    }
            }));
    }
    
    
}