/**
 * @file settings-tab.ts
 * @description
 * The main configuration UI for the plugin.
 * * AI CONTEXT & ARCHITECTURE NOTE:
 * This UI manages the 1-hour Custom Token exchange. The user pastes the code generated by
 * the React app, clicks "Connect", and the SDK trades it for a permanent Refresh Token via
 * Google Identity Toolkit. The 1-hour code is immediately discarded.
 * * Linter strictness: `eslint-plugin-obsidianmd` is heavily disabled locally here to allow 
 * capitalized acronyms like "API", "URL", and "Firebase".
 */

import { App, PluginSettingTab, Setting, Notice } from 'obsidian';
import SelfStatsPlugin from '../main';

export class SelfStatsSettingTab extends PluginSettingTab {
    plugin: SelfStatsPlugin;

    constructor(app: App, plugin: SelfStatsPlugin) {
        super(app, plugin);
        this.plugin = plugin;
    }

    display(): void {
        const {containerEl} = this;
        containerEl.empty();

        new Setting(containerEl).setName('Connection configuration').setHeading();

        new Setting(containerEl)
            // // eslint-disable-next-line obsidianmd/ui/sentence-case
            .setName('Firebase API key')
            // eslint-disable-next-line obsidianmd/ui/sentence-case
            .setDesc('Your public web API key from Firebase.')
            .addText(text => text
                // eslint-disable-next-line obsidianmd/ui/sentence-case
                .setPlaceholder('AIzaSy...')
                .setValue(this.plugin.settings.firebaseApiKey)
                .onChange(async (value) => {
                    this.plugin.settings.firebaseApiKey = value;
                    await this.plugin.saveSettings();
                    this.plugin.initializeSdk(); 
                }));

        new Setting(containerEl)
            // // eslint-disable-next-line obsidianmd/ui/sentence-case
            .setName('Backend URL')
            .setDesc('Local emulator or live cloud function endpoint.')
            .addText(text => text
                .setPlaceholder('http://127.0.0.1:5001/...')
                .setValue(this.plugin.settings.backendUrl)
                .onChange(async (value) => {
                    this.plugin.settings.backendUrl = value;
                    await this.plugin.saveSettings();
                    this.plugin.initializeSdk();
                }));

        new Setting(containerEl).setName('Authentication').setHeading();
        
        let setupCodeInput = "";

        new Setting(containerEl)
            .setName('Connect integration')
            .setDesc(this.plugin.settings.refreshToken 
                ? 'System is authenticated. Generate a new setup code to overwrite.' 
                : 'Paste your 1-hour setup code from the React dashboard.')
            .addText(text => text
                .setPlaceholder('Setup code')
                .onChange(value => {
                    setupCodeInput = value;
                }))
            .addButton(button => button
                .setButtonText('Connect')
                .setCta()
                .onClick(async () => {
                    if (!setupCodeInput) {
                        new Notice("Please enter a setup code first.");
                        return;
                    }
                    
                    button.setButtonText("Connecting...");
                    button.setDisabled(true);

                    try {
                        // eslint-disable-next-line @typescript-eslint/no-unsafe-call
                        await this.plugin.client.exchangeSetupCode(setupCodeInput);
                        
                        // eslint-disable-next-line obsidianmd/ui/sentence-case
                        new Notice("✅ Authentication successful!");
                        this.display(); 
                    } catch (error) {
                        console.error(error);
                        
                        // eslint-disable-next-line obsidianmd/ui/sentence-case
                        new Notice("❌ Failed to connect. Check the console for details.");
                        button.setButtonText("Connect");
                        button.setDisabled(false);
                    }
                }));
    }
}