
import { ObsidianConfig } from '../types';

/**
 * Sends a journal entry to the local Obsidian vault using the Local REST API plugin.
 */
export const sendToObsidian = async (
  config: ObsidianConfig,
  payload: { title: string; content: string; metadata: any }
): Promise<{ success: boolean; response: string }> => {
  if (!config.apiKey || !config.host) {
    return { success: false, response: 'Missing Obsidian configuration details.' };
  }

  const protocol = config.useHttps ? 'https' : 'http';
  const baseUrl = `${protocol}://${config.host}:${config.port}`;
  
  // Sanitize title for filename
  const fileName = payload.title.replace(/[/\\?%*:|"<>]/g, '-') + '.md';
  const folderPath = config.targetFolder.endsWith('/') ? config.targetFolder : config.targetFolder + '/';
  const fullPath = encodeURIComponent(`${folderPath}${fileName}`);

  const markdownContent = `---
date: ${new Date().toISOString()}
domain: ${payload.metadata.analysis?.domainType || 'N/A'}
activity: ${payload.metadata.analysis?.activityType || 'N/A'}
source: Neural Second Brain
---

# ${payload.title}

${payload.content}

## AI Analysis
- **Domain**: ${payload.metadata.analysis?.domainType}
- **Activity**: ${payload.metadata.analysis?.activityType}
- **Duration**: ${payload.metadata.analysis?.duration}

### Weighted Actions
${payload.metadata.analysis?.weightedActions?.map((wa: any) => `- ${wa.label} (${(wa.weight * 100).toFixed(0)}%)`).join('\n')}

---
*Generated by Neural Second Brain*
`;

  try {
    const response = await fetch(`${baseUrl}/vault/${fullPath}`, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${config.apiKey}`,
        'Content-Type': 'text/markdown',
      },
      body: markdownContent,
    });

    if (response.ok) {
      return { success: true, response: 'Note created in Obsidian vault' };
    } else {
      const errorText = await response.text();
      return { success: false, response: `Obsidian API Error: ${response.status} - ${errorText}` };
    }
  } catch (err: any) {
    return { success: false, response: `Connection Failed: ${err.message}. Ensure Obsidian is open and the Local REST API plugin is active.` };
  }
};
